name: Perform zip deployment

on:
  workflow_dispatch:
    inputs: 
      auth: 
        type: string
        required: true
      repo:
        type: string
        required: true

  workflow_call:
    inputs: 
      scm_url:
        required: true
        type: string
      artifact_name: 
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps: 
    - name: "Download artifact"
      uses: dawidd6/action-download-artifact@v2
      with:
        # name: ${{ inputs.artifact_name }}
        github_token: ${{ github.event.inputs.auth }}
        repo: ${{ inputs.repo || github.repository }}
        check_artifacts: true
        # run_id: ${{inputs.run_id}}

    - name: "Display"
      run: |
        ls -la 
        # zip -sf app.zip

    # - name: "Deploy azure"
    #   run: | 
    #     http_res=$(curl -s -v -o dev/null -w "%{http_code}" \
    #       -X POST ${{ inputs.scm_url }} \
    #       -u "${{ secrets.ZIP_DEPLOY_GLOBAL_SCOPE_USER_CREDENTIALS }}" \
    #       -T app.zip)
    #     [[ $http_res = "200" ]] && echo "Deployment successful" || exit 1;